---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts (Main Page)
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: document
  path: _includes/sidebar.html
  label: Website Sidebar
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
